### ISSUE TITLE
Easy way to convert a struct to a document

### ISSUE THREAD

**Issue by hybrisCole** [mongodb/bson-rust#140]
Hi, I have the following code:

```rust
pub async fn insert_many_sample(
    samples: Vec<Sample>,
) -> Result<u8, mongodb::error::Error> {
    let db = get_database().await?;
    let collection = db.collection("sample");
    let samples_bson: Vec<bson::ordered::OrderedDocument> =
        samples.into_iter().map(|x| {
            let serialized = bson::to_bson(&x).unwrap();
            let doc = doc!{"data": serialized.clone()};
            doc
        }).collect();
    collection.insert_many(samples_bson, None)?;
    Ok(1)
}
```
is there a way to not have to create the "data" parent field and have the `doc` variable with the same structure as `serialized`?

Regards,

**Comment by saghm** [comment]
One thing you could do is make another struct that contains a `Sample` and then serialize that. It would look something like this

```rust
#[derive(Serialize)]
struct SampleWrapper {
	data: Sample
}

impl From<Sample> for SampleWrapper {
    fn from(data: Sample) -> Self {
        Self { data } 
    }
}

pub fn insert_many_sample(
    collection: &Collection,
    samples: Vec<Sample>,
) -> Result<u8, mongodb::error::Error> {
    let samples: Result<Vec<_>> = samples
        .into_iter()
        .map(|sample| {
            bson::to_bson(&SampleWrapper::from(sample))
        })
        .collect()
    collection.insert_many(samples?, None)?;
    Ok(1)
}
```

On a tangential note, the driver currently doesn't have any async support, so the call to `insert_many` will block on reading the server response. This means you might not want to use it in an async function.

**Comment by hybrisCole** [comment]
This is how I fixed but I'm still not 100% sure this is good, besides the async issue you told me:

```rust
pub async fn insert_many_sample(
    samples: Vec<Sample>,
) -> Result<u8, mongodb::error::Error> {
    let db = get_database().await?;
    let collection = db.collection("sample");
    let samples_bson: Vec<bson::ordered::OrderedDocument> =
        samples.into_iter().map(|x| {
            let bson_data = bson::to_bson(&x).unwrap();
            let mut doc = Document::new();
            if let bson::Bson::Document(document) = bson_data { //this part did the trick
                doc = document;
            }
            doc
        }).collect();
    collection.insert_many(samples_bson, None)?;
    Ok(1)
}```

**Comment by saghm** [comment]
Apologies; I originally misunderstood your question and thought you were asking how to nest the document under the `data` field without using the macro, but I understand now that what you're asking is how to avoid needing the extra field.

The solution you gave works reasonably well. One way I might suggest improving it is to create your own error type instead of just wrapping the driver's error so that you can return a custom error if serializing the struct doesn't return a document. You can take advantage of the fact that an iterator over `Result<T, E>` can `collect` into a `Result<Vec<T>, E>>`; if an error is yielded by the iterator, it will return that, but if not, it will return a vector of all of the items. This will also let you avoiding using `unwrap`, which would otherwise panic if an error was returned. Assuming your error type implements `From<mongodb::error::Error>`, and method called `non_document_serialized` to construct the custom error, it would look something like this:

```rust
pub fn insert_many_sample(
    collection: &Collection,
    samples: Vec<Sample>,
) -> Result<u8, Error> {
    let samples: Result<Vec<_>> = samples
        .into_iter()
        .map(|sample| {
            match bson::to_bson(&SampleWrapper::from(sample)) {
                Bson::Document(doc) => Ok(doc),
                other => Err(Error::non_document_serialized(other)),
            }
        })
        .collect()
    collection.insert_many(samples?, None)?;
    Ok(1)
}
```

It might be worth adding a `to_document` helper to the library at some point to provide this behavior built-in; we certainly have some places in the driver that we could use it.

**Comment by saghm** [comment]
It's been a few weeks since the last response, so I'm going to assume that the issue is solved. Thanks for using the library!
