### ISSUE TITLE
Deserialise ObjectId from String

### ISSUE THREAD

**Issue by jeans11** [mongodb/bson-rust#217]
Hi!

Is there a way to deserialise a string to an ObjectId (without `$oid` map)

```rust
#[derive(Debug, Deserialize)]
struct Foo {
    foo: Option<Vec<ObjectId>>,
}

fn main() {
    let json = r#"
        {
            "foo": ["5f7ac845d20c290001a1ded3"]
        }
    "#;

    println!("{:?}", serde_json::from_str::<Foo>(&json)); // Error
}
```

Or the only way is to create a custom deserialiser function for the `Option<Vec<ObjectId>>` type?

**Comment by isabelatkinson** [comment]
Hi @jeans11!

The best way to do this is to create a custom deserializer function for the `foo` field using the Serde `deserialize_with` attribute. [8d8cffe](https://github.com/mongodb/bson-rust/commit/8d8cffe171d848a50fe26958c7f4187d0af2e4a6) includes an implementation of the `FromStr` trait for `ObjectId`, so that can be used to create an `ObjectId` from the string present in `json`. Otherwise, you'll need to include the `$oid` mapping in your JSON string.

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-602
