### ISSUE TITLE
How to write BSON to disk?

### ISSUE THREAD

**Issue by vedantroy** [mongodb/bson-rust#238]
I can create a bson value, but how do I actually serialize it to disk? I'm having trouble finding a way to convert a bson value into bytes.

**Comment by patrickfreed** [comment]
You can write BSON to bytes via [`Document::to_writer`](https://docs.rs/bson/1.2.0/bson/document/struct.Document.html#method.to_writer) and read BSON from bytes via [`Document::from_reader`](https://docs.rs/bson/1.2.0/bson/document/struct.Document.html#method.from_reader). In BSON, a Document is the only top-level type, so we provide this functionality on `Document` only rather than on `Bson`. Note that these methods work on anything that implement `Write` and `Read` respectively, so they could also be used to write to and read from more than just the file system.

e.g.
```rust
let doc = doc! { "x": 1, "hello": "world" };              
                                                          
{                                                         
    let mut f = File::create("foo.bson").unwrap();        
    doc.to_writer(&mut f).unwrap();                       
}                                                         
                                                          
{                                                         
    let mut f = File::open("foo.bson").unwrap();          
    let read_doc = Document::from_reader(&mut f).unwrap();
    assert_eq!(read_doc, doc);                            
    println!("{}", read_doc);                             
}                                                         
```

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-689

**Comment by agolin95** [comment]
Have not heard back for some time, closing out this thread. Please feel free to leave us a comment here and we can reopen this thread, or feel free to file a new issue to continue the conversation.
