### ISSUE TITLE
Creating a BSON document from quote-less keys

### ISSUE THREAD

**Issue by Im-Stevemmmmm** [mongodb/bson-rust#253]
In MongoDB, you can insert a BSON document with quote-less keys. For example,

```
db.inventory.insertOne(
    { item: "canvas", qty: 100, tags: ["cotton"], size: { h: 28, w: 35.5, uom: "cm" }
})
```

Is there some way to convert something such as `String::from("{ key: \"value\" }")` to a `Document`? 

In Go, it is possible with the `UnmarshallJSON` function from the package `"gopkg.in/mgo.v2/bson"`. ([Source code here](https://github.com/go-mgo/mgo/blob/a6b53ec6cb22/bson/json.go#L14))

Thanks again.

**Comment by agolin95** [comment]
Tracked in https://jira.mongodb.org/browse/RUST-771

**Comment by patrickfreed** [comment]
Hi @Im-Stevemmmmm, sorry for the late response!

`Document` itself doesn't perform any JSON-specific parsing but rather just implements the more general `Serialize` and `Deserialize` traits from [`serde`](https://serde.rs). This allows for a `Document` to be serialized to and deserialized from JSON (or any other `serde`-compatible format) via any `serde`-compatible JSON crate, such as [`serde_json`](https://docs.rs/serde_json) . This also means that whether or not quoted keys are accepted is not really up to us, but is instead up to the JSON crate.

e.g. when using `serde_json`, unquoted keys are not accepted:
```rust
let d: serde_json::Result<Document> = serde_json::from_str("{ \"x\": 1 }");
println!("{:?}", d);                                                       
let d1: serde_json::Result<Document> = serde_json::from_str("{ x: 1 }");   
println!("{:?}", d1);                                                      
```
yields:
```
Ok(Document({"x": Int32(1)}))
Err(Error("key must be a string", line: 1, column: 3))
```
So unfortunately, unless there is another `serde`-compatible JSON library out there, you won't be able to have this work with `Document`. Note that this is not unexpected, however, since [the JSON format does not allow for unquoted keys](https://stackoverflow.com/questions/949449/do-the-json-keys-have-to-be-surrounded-by-quotes). The reason the shell works with them is because the shell is essentially a specialized JavaScript interpreter, and JavaScript allows for its object keys to be unquoted. For more information on the differences between JSON and JavaScript, see [this StackOverflow post](https://stackoverflow.com/a/3975890).
