### ISSUE TITLE
RUST-811 Easier Access to the inner field of DateTime

### ISSUE THREAD

**Issue by AsianIntel** [mongodb/bson-rust#256]
In the `eliminating public deps` commit, the `DateTime` struct was clearly re-worked upon. Due to the removal of the `Deref` impl, it has become less obvious how to access the inner `chrono::DateTime` field unless you notice the `From` impl on it.

Two ways to remedy are:
```rust
chrono::DateTime::<Utc>::from(foo)
```
or
```rust
foo.into()
```
but this will sometimes require a type annotation

Asking whether we could maintain the `Deref` impl (and `DerefMut`) or provide a method to access the inner field. For e.g. `as_datetime()` to return a reference and `into_datetime` to return the inner `chrono::DateTime` & consume `bson::DateTime`

**Comment by patrickfreed** [comment]
Hi @AsianIntel, thanks for reporting this issue! You make a good point that the interop between `bson::DateTime` and `chrono::DateTime` isn't as obvious or ergonomic as it could be, so we'll be working to improve this shortly. You can track the progress of any changes to this via the RUST-811 Jira ticket. Thanks!

**Comment by AsianIntel** [comment]
Alright, thank you so much for the quick response!!

**Comment by patrickfreed** [comment]
Hi again @AsianIntel! We just merged in #258 which contains some ergonomic improvements for `bson::DateTime`, notably the `DateTime::from_chrono` and `DateTime::to_chrono` methods. In order to access this functionality, you'll need to specify the `"chrono-0_4"` feature flag now, however.

Unfortunately, we weren't able to include any methods that returned a reference as the inner value is no longer a `chrono::DateTime`. Check out #258's description for more info.

**Comment by AsianIntel** [comment]
Hey, thanks for the quick update, I kind of have a comment, which is, I think it would be better to mark `to_chrono_private` as `pub(crate)` and remove the duplicate `to_chrono`

**Comment by patrickfreed** [comment]
This was mostly done as a convenience for us so we wouldn't have to type out `_private` at all the internal call sites and could just use `to_chrono` as if the feature flag were enabled. It shouldn't have any effect on the public API.
