### ISSUE TITLE
Use uuid in 2.0

### ISSUE THREAD

**Issue by AurelienFT** [mongodb/bson-rust#272]
I want to switch from bson 1.2 to 2.0 and I use `uuid`.

I just saw that there is some changes with them but the tests are just on old versions (https://github.com/mongodb/bson-rust/blob/master/src/tests/serde.rs#L558). Is that possible to have a test or a documentation on how to have the same behavior as before but with the new way.

Thank you !

**Comment by patrickfreed** [comment]
In 2.0.0-beta.1, the `uuid` interop was moved behind a feature flag to help protect us from breaking changes in the `uuid` crate in the future (since it's pre 1.0). In order to use it with `bson`, you'll now need to add the feature flag to your `Cargo.toml`:

```toml
bson = { version = "2.0.0-beta.1", features = ["uuid-0_8"] }
```
or if you get `bson` via the `mongodb` crate:
```toml
mongodb = { version = "2.0.0-beta.1", features = ["bson-uuid-0_8"] }
```
And now `Uuid` can be used as it was in 1.2:
```rust
#[derive(Debug, Deserialize, Serialize)]
struct MyType {
    #[serde(with = "bson::serde_helpers::uuid_as_binary")]
    uuid: Uuid
}
```

We also added support for working with UUIDs stored in the various other legacy formats used by the Python, Java, and C# drivers. Those can be accessed via the various serde helpers (e.g. `uuid_as_python_legacy_binary`).

Regarding the documentation, apologies for it being sparse right now! We're currently waiting until the `2.0.0` stable release is ready before updating the READMEs and such. In the meantime, check out the [release notes](https://github.com/mongodb/bson-rust/releases/tag/v2.0.0-beta.1) for descriptions of the various changes from 1.2.

Please let us know if you have any more questions / issues!

**Comment by AurelienFT** [comment]
Hello,

Thank you for your fast answer I forget to check for release notes that's my bad. It's very well documented on release notes for a beta version. Keep going !
