### ISSUE TITLE
[Idea] May be it's helpful to provide some remove methods for documents?

### ISSUE THREAD

**Issue by WindSoilder** [mongodb/bson-rust#292]
Sometimes I runs into scenario that needs to take ownership of inner `String` value (because I don't want to clone it), currently I have to write something like this:

```rust
use bson::{Bson, Document};
// Result is my custom defined type.
/// Remove a string value and return it, if given key exists and has the correct type.
pub fn remove_string(doc: &mut Document, key: &str) -> Result<String> {
    let _ = doc.get_str(key)?;
    if let Some(Bson::String(s)) = doc.remove(key) {
        return Ok(s);
    }
    panic!("It shouldn't happened, because the `key` is already checked in `doc`.");
}
```

I think it's helpful to make it to be a public method of `Document`.  Many other types doesn't need a helper remove method like this, because these types are `Copy`, I don't know if it's useful to provide something like `remove_array`, `remove_document` (because I don't meet the scenario for now).

**Comment by patrickfreed** [comment]
Hi @WindSoilder, thanks for the suggestion! 

For situations like this where the schema (both name and type) are well known, its generally better to use `serde` to deserialize rather than methods directly on `Document`.

e.g.
```rust
#[derive(Deserialize)]
struct MyData { x: String }

let doc = doc! { "x": "my string" };
let data: MyData = bson::from_document(doc)?;
println!("{}", data.x);
```

Due to the large number of methods required to support this feature (one per BSON type) and that a simple workaround or serde can be used here, we've decided not to implement this API. 

Thanks again for your suggestion, and if you have any more questions about this, please do let us know.
