### ISSUE TITLE
Convert Vec<Bson, Global> to Vec<String>

### ISSUE THREAD

**Issue by teooliver** [mongodb/bson-rust#320]
Question:

Im trying to use the `.distinct` method to get all ‘_ids’ in a collection. The `.distinct` method returns a `Vec<Bson, Global>` type and I would like to convert that to a `Vec<String>`.
I tried everything I could but can't figure this one out.

Here's a snippet of the function Im trying to build:

```rust

 pub async fn get_all_clients_ids(&self) -> Result<Vec<String>, error::Error> {
        let clients_ids = self
            .get_clients_collection()
            .distinct("_id", None, None)
            .await
            .map_err(MongoQueryError)?;

        // The `.distinct` method returns a Vec<Bson, Global>
        // I would like to convert clients_ids from Vec<Bson, Global> to Vec<String>.
        // I tried everything I could but can't figure this one out.

        // Should I iterate over each item in clients_ids and convert them individualy to String?
        // In that cause how can I do that?

        let string_vec: Vec<String>;
        for item in clients_ids {
            // serialize_object_id_as_hex_string(item);
            // let x: std::result::Result<String, mongodb::bson::de::Error> = bson::from_bson(item);

            // TODO
            // convert item from Bson to String
            // push to string_vec.
            println!("Bson Item {:?}", item); // prints ObjectId("61842402bcfb83e1b27b6d85")
        }

        
        Ok(string_vec)
}

```

Thank you all in advance for the help.

**Comment by abr-egn** [comment]
Because there's no way for the Rust driver to know the type of the field being queried in the `distinct` call, it returns the result as [BSON values](https://docs.rs/bson/2.0.1/bson/#bson-values).  Since the values you're querying are of type `ObjectId`, you may want to change your function signature to

```Rust
pub async fn get_all_clients_ids(&self) -> Result<Vec<bson::oid::ObjectId>, error::Error>
```

to preserve that type information.

To translate from the `Vec<Bson>` to a `Vec<bson::oid::ObjectId>`, you can use the `Bson::as_object_id` method:

```Rust
let oid_vec: Vec<bson::oid::ObjectId>;
for item in clients_ids {
    if let Some(oid) = item.as_object_id() {  // convert item from Bson to ObjectId
        oid_vec.push(oid);  // push to oid_vec.
    } else {
        // TODO handle unexpected type
    }
}
```

This can also be written in a stream-processing/functional style by using the convenient behavior of `collect` for `Option`s:

```Rust
let maybe_oid_vec: Option<Vec<bson::oid::ObjectId>> =  clients_ids.into_iter()  // convert Vec to impl Iterator<Item=Bson>
    .map(Bson::as_object_id)  // convert Item from Bson to Option<ObjectId>
    .collect();  // convert iterator to Option<Vec<ObjectId>>
```

Note that in either case your function will still need to handle the case where any of the fields were not the expected type; what to do in that case is up to your particular application.

If you do specifically need `String` values instead of `ObjectId`, the `ObjectId::to_hex` method provides that conversion.

**Comment by teooliver** [comment]
@abr-egn Thank you so much! That was exactly what I needed. =)
