### ISSUE TITLE
DateTime written as String with "insert_one" function but then changed to Datetime object with 'update_one'

### ISSUE THREAD

**Issue by kinwolfqc** [mongodb/bson-rust#336]
Hi,
  I am new to using this driver(and mongoDb too), and I'm confused about this particular behavior:

I have a struct(see below for the struct) to create courses, with a chrono::Datetime<utc> field.  When I create a new course and write it in mongodb with `insert_one`:
`let resp = collection.insert_one(new_course, None).await?;`
the course_datetime field is written as a String in the DB. 
[String field](https://i.imgur.com/QgKkQkq.png)

```Rust
pub struct CreateCourse {
    pub tutor_id: ObjectId,
    pub course_name: String,
    pub course_description: Option<String>,
    pub course_format: Option<String>,
    pub course_structure: Option<String>,
    pub course_type_id: ObjectId,
    pub course_duration: Option<String>,
    pub course_price_in_cents: Option<i32>,
    pub course_level: Option<String>,
    pub course_datetime: DateTime<Utc>,
    
}
```

but then I wrote a new handler to update a course, and I am using `update_one `with the doc! macro with $set for that, but when I commit to the database, it is changing the String field to a Datetime one. 
[Now a Datetime field](https://i.imgur.com/3ha08Z0.png)
```Rust
 let update_result = collection.update_one(

        doc! {     
            "_id": &course_id,
        },         
        doc! {
            "$set": { 
                "course_name": new_course_record.course_name,
                "course_description": new_course_record.course_description,
                 "course_format": new_course_record.course_format,
                 "course_structure": new_course_record.course_structure,
                 "course_type_id":new_course_record.course_type_id ,
                 "course_duration": new_course_record.course_duration,
                 "course_price_in_cents":new_course_record.course_price_in_cents ,
                 "course_level": new_course_record.course_level,
                 "course_datetime": new_course_record.course_datetime,
         }     
        },
     
        None,         
     ).await?;
```

 This is causing all kind of trouble since once a course is updated, the handler to get back the course details fails, since it was expecting a String and is now receiving a map instead(the Datetime object)

>     "error": "The server returned an invalid reply to a database operation: invalid type: map, expected a formatted date and time string or a unix timestamp"

What am I doing wrong here?  Why is "update_one" writing it as a string, but the doc! macro writing the same information as a Datetime object?  What should be done to make both behave the same way?  Is there a way to make `insert_one`write the information as a Datetime object too?(that would be ideal)

**Comment by isabelatkinson** [comment]
Hi @kinwolfqc, thank you for filing this issue! Due to the way `Serialize` and `Deserialize` are implemented for the `chrono::DateTime` type, `chrono::DateTime`s are serialized as strings when added to the database using `insert_one`. On the other hand, the `doc` macro uses this [`From`](https://docs.rs/bson/latest/bson/enum.Bson.html#impl-From%3CDateTime%3CT%3E%3E) implementation when a `chrono::DateTime` is passed in to construct a `Bson::DateTime`, which will appear as a datetime in the database. This discrepancy is what is causing different types to be present in your database. You can read [here](https://github.com/mongodb/bson-rust/#working-with-datetimes) for more information about working with datetimes.

For this particular example, it would be best to determine which type (i.e. datetime vs. string) you want to exist in your database. If you want the data to be represented as datetimes, I'd recommend either changing the type of the `course_datetime` field to be a `bson::DateTime` which will be serialized as a datetime when added to the database, or using the [`chrono_datetime_as_bson_datetime`](https://docs.rs/bson/latest/bson/serde_helpers/chrono_datetime_as_bson_datetime/index.html) helpers to do this conversion when serializing/deserializing. If you want the data to be represented as strings, the `course_datetime` field can be left as-is and `to_string` can be called in the `doc` macro on `course_datetime` to avoid the datetime conversion.

Please let me know if you have any further questions!

**Comment by kinwolfqc** [comment]
@isabelatkinson Hi, thansk for the tips.  I went the `chrono_datetime_as_bson_datetime` way and it is working fine now(I changed the rest of the code to expect DateTime too instead of String).  Creating a new course now add the date as a datetime object, and the update part still work fine.  Thanks! :)
