### ISSUE TITLE
Serializing a BSON document to a simple JSON

### ISSUE THREAD

**Issue by erfanium** [mongodb/bson-rust#354]
I wonder is there any way to serialize a bson document to a simple json (not extjson)?
I know there's two similar methods `Bson::into_relaxed_extjson` and `Bson::into_canonical_extjson` but they convert them into extjson, not simple json, which i don't want.

Here's is an example of my expected result.
```rs
let doc = bson!({ "x": 5i32, "_id": oid::ObjectId::new(), "d": bson::DateTime::now() });


let simple_json = doc.clone().into_simple_json();
println!("{}", simple_json); // { "x": 5, "_id": <hexstring>, "d": "2020-06-01T22:19:13.075Z" }
```

This is exactly the same behavior of `JSON.stringify(bson_document)` in JavaScript

**Comment by kmahar** [comment]
Hi @erfanium, thanks for reaching out.

There isn't a way to do this directly from a `Bson` right now.

We recently discussed doing something that might help in this case: [RUST-1178](https://jira.mongodb.org/browse/RUST-1178). See #191 for some related discussion. What that ticket proposes is adding a way to opt into having the driver produce "plain" JSON for types such as `bson::DateTime` and `oid::ObjectId`. 

One workaround currently available would be to define a type modeling your data that implements `Serialize` and `Deserialize`. You could then deserialize your BSON data into that type, and serialize the type into plain JSON. See [here](https://github.com/mongodb/bson-rust#modeling-bson-with-strongly-typed-data-structures) for some details on how to do that. 
Beyond that, another option would be to implement your own logic, something like [this](https://github.com/mongodb/bson-rust/blob/b62338a56f8e63af63b131e918ce3da63094495c/src/bson.rs#L378-L466), that serializes BSON types the way you want them to be represented.

**Comment by erfanium** [comment]
Thank you @kmahar 
> another option would be to implement your own logic, something like [this](https://github.com/mongodb/bson-rust/blob/b62338a56f8e63af63b131e918ce3da63094495c/src/bson.rs#L378-L466)

I wanna add that it's not really my own logic, MongoDB Atlas Data Api uses this logic for response bodies.
https://www.mongodb.com/docs/atlas/api/data-api-resources/#find-a-single-document

**Comment by kmahar** [comment]
@erfanium Atlas Data API supports both plain and extended JSON, with the caveat that the plain format can lead to data loss because not all BSON types are representable in plain JSON (see [docs](https://www.mongodb.com/docs/atlas/app-services/endpoints/#return-types)).
An additional caveat worth noting is that even for types that can be represented in plain JSON, it is impossible for many of them to be losslessly round-tripped from `Document` -> JSON -> `Document`. For example, the "plain" JSON of an `ObjectId` is a string, and so if you have a document like `doc! { "_id": oid::ObjectId::new() }`, serialize it to plain JSON, and then deserialize the JSON back into a `Document`, the BSON library cannot tell that the field was initially an `ObjectId`, and so it will be decoded as a string instead: `doc! { "_id": "string_representation_here" }`. 

Due to these limitations, we've chosen not to support plain JSON in this library at this time. If you want to use this BSON library with Atlas Data API I would strongly recommend having your endpoints return and accept extended JSON, as it will ensure you do not lose any data or inadvertently change the data type of any fields in your documents.

**Comment by erfanium** [comment]
@kmahar

> Atlas Data API supports both plain and extended JSON, with the caveat that the plain format can lead to data loss because not all BSON types are representable in plain JSON (see [docs](https://www.mongodb.com/docs/atlas/app-services/endpoints/#return-types)).

That was all I need, Thank you!

**Comment by gamertike** [comment]
I would like to quickly bring this back and ask: since we cannot make both JSON and BSON with one struct, is there really a point of using bson features like uuids and dates instead of just strings?

**Comment by erfanium** [comment]
@gamertike databases can perform more optimizations when they know a field is a UUID, and it's not a random string.

also it helpd data integrity

**Comment by gamertike** [comment]
> @gamertike databases can perform more optimizations when they know a field is a UUID, or Date
> also it helps data integrity 

Then what can i really do bc i do not want to have to send bson through my rest api to clients? It makes no sense to do that. I would like a solution that avoids rewriting all fields into a new struct, but if i have to, i can try to make it work, but i feel it will become harder to manage my codebase.
