### ISSUE TITLE
Provide a helper method to deserialize a stream of BSON

### ISSUE THREAD

**Issue by hamza1311** [mongodb/bson-rust#412]
Provide a helper function similar to the one provided by the  JS library: [deserializeStream](https://github.com/mongodb/js-bson#deserializeStream). 

The the function can look like:
```rust
fn bson_from_stream(bytes: &[u8]) -> bson::de::Result<Vec<Document>> {
    let max_len = bytes.len() as u64;
    let mut cur = Cursor::new(bytes);
    let mut docs = Vec::new();
    while cur.position() != max_len {
        let document = Document::from_reader(&mut cur)?;
        docs.push(document)
    }
    Ok(docs)
}
```

The above function is only for demonstration purposes and shouldn't directly be copy pasted. It does not take into many things, such as what happens if reading fails, if there is too much data in the buffer, etc

**Comment by isabelatkinson** [comment]
Hi @hamza1311, apologies for the late reply! Because we already provide the `Document::from_reader` method, we have decided not to add this method to read in multiple documents. There are various ways to handle the possible errors you described, and we'd rather leave it up to individual users to determine the best course of action.

Please feel free to file another issue if you have any further questions or requests.
