### ISSUE TITLE
Generalize From impls for Bson::Array and Bson::Document

### ISSUE THREAD

**Issue by kyeah** [mongodb/bson-rust#55]
Currently we only implement `From<Array>` and `From<Document>`; however, we should be able to implement the more generalized `FromIterator<Bson>` and `FromIterator<(String, Bson)>` traits for these two objects.

**Comment by zonyitoo** [comment]
Agree.

**Comment by saghm** [comment]
This is available as part of the current API; `Document` [implements `FromIterator`](https://docs.rs/bson/0.14.0/bson/ordered/struct.OrderedDocument.html#implementations), and `Array` is an alias of `Vec<Bson>`, and since `Vec<T>` already implements `FromIterator<T>`, `FromIterator<Bson>` is available for `Array`.
